help:
	@echo "	--- Make cmds ---"
	@echo "clean: rm all superfluous files"
	@echo "quine: execute all .py files"

clean:
	rm -rf Grace_kid.py
	rm -rf Sully_*

quine:
	python3 Colleen.py
	Grace.py
	Sully.py
